service: semi-auto-api-call

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1

functions:
  now:
    handler: handler.now
    events:
      - http:
          path: now
          method: get
