service: semi-auto-api-call

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

custom:
  defaultStage: dev
  environment:
    dev: ${file(./env/dev.yml)}
    prod: ${file(./env/prod.yml)}  

functions:
  now:
    handler: handler.now
    events:
      - http:
          path: now
          method: get

  post-now:
    handler: handler.now_to_slack
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - http:
          path: post-now
          method: post
